name: E2E Provision and Test

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      name:
        type: string
        required: true

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4.1.7
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: '~1.25'
          cache-dependency-path: "**/*.sum"

      - name: Azure login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Provision Infrastructure
        shell: bash
        run: go run ./cmd/e2e/main.go infra --subscription="${{ secrets.AZURE_SUBSCRIPTION_ID }}" --tenant="${{ secrets.AZURE_TENANT_ID }}" --names="${{ inputs.name }}" --infra-file="./infra-${{ inputs.name }}.json"

      - name: Upload infra file
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: infra-${{ inputs.name }}
          path: infra-${{ inputs.name }}.json
  test:
    needs: provision
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4.1.7
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: '~1.25'
          cache-dependency-path: "**/*.sum"

      - name: Azure login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: infra-${{ inputs.name }}

      - name: Test
        shell: bash
        id: test
        run: go run ./cmd/e2e/main.go deploy --infra-file="./infra-${{ inputs.name }}.json"

      - name: Print test logs
        shell: bash
        run: echo "printing first 100 lines and last 200 lines of e2e logs..." && head -n 100 job-app-routing-operator-e2e.log && tail -n 200 job-app-routing-operator-e2e.log
        if: always() && (steps.test.outcome == 'failure' || steps.test.outcome == 'success')
