name: E2E Provision and Test

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      name:
        type: string
        required: true

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '~1.25'
          cache-dependency-path: "**/*.sum"

      - name: Azure login
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Provision Infrastructure
        shell: bash
        run: go run ./cmd/e2e/main.go infra --subscription="${{ secrets.AZURE_SUBSCRIPTION_ID }}" --tenant="${{ secrets.AZURE_TENANT_ID }}" --names="${{ inputs.name }}" --infra-file="./infra-${{ inputs.name }}.json"

      - name: Upload infra file
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: infra-${{ inputs.name }}
          path: infra-${{ inputs.name }}.json
  test:
    needs: provision
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '~1.25'
          cache-dependency-path: "**/*.sum"

      - name: Azure login
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: infra-${{ inputs.name }}

      - name: Test
        shell: bash
        id: test
        run: go run ./cmd/e2e/main.go deploy --infra-file="./infra-${{ inputs.name }}.json"

      - name: Print test logs
        shell: bash
        run: echo "printing first 100 lines and last 200 lines of e2e logs..." && head -n 100 job-app-routing-operator-e2e.log && tail -n 200 job-app-routing-operator-e2e.log
        if: always() && (steps.test.outcome == 'failure' || steps.test.outcome == 'success')
