name: Image Vulnerability Scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily

permissions:
    contents: read

jobs:
  gen-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #v4.1.1
      - id: set-matrix
        run: |
          matrix=$(cat active_releases.json | tr '\n' ' ')
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  scan:
    needs: gen-matrix
    strategy:
      matrix: ${{ fromJSON(needs.gen-matrix.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/trivy.yaml
    name: ${{ matrix.name }} scan
    with:
      name: ${{ matrix.name }}
      operator: ${{ matrix.operator }}
      nginx: ${{ matrix.nginx }}
      externaldns: ${{ matrix.externaldns }}