name: Trivy

on:
  workflow_call:
    inputs:
      name:
        type: string
      operator:
        type: string
        required: true
      nginx:
        type: string
        required: true
      externaldns:
        type: string
        required: true

jobs:
  operator:
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@c1824fd6edce30d7ab345a9989de00bbd46ef284 # v0.34.0
        with:
          image-ref: ${{ inputs.operator }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@c1824fd6edce30d7ab345a9989de00bbd46ef284 # v0.34.0
        with:
          image-ref: ${{ inputs.nginx }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  externaldns:
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@c1824fd6edce30d7ab345a9989de00bbd46ef284 # v0.34.0
        with:
          image-ref: ${{ inputs.externaldns }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

         
